---
apiVersion: v1
kind: Namespace
metadata:
  name: overpass
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: overpass
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: api-tailscale
spec:
  selector:
    statefulset.kubernetes.io/pod-name: api-0
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-tailscale
  namespace: overpass
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: api-tailscale
      port:
        name: http
  tls:
    - hosts:
      - overpass
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
  namespace: overpass
spec:
  selector:
    matchLabels:
      app: api
  serviceName: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/dzfranklin/overpass-api:v0.40
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - containerPort: 80
              name: http
          env:
            - name: METRICS_API_KEY
              valueFrom:
                  secretKeyRef:
                    name: metrics-api-key
                    key: key
      volumes:
        - name: data
          hostPath:
            path: /mnt/overpass-data
