---
apiVersion: v1
kind: Namespace
metadata:
  name: overpass
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: overpass
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: api-tailscale
  annotations:
    tailscale.com/hostname: overpass-api
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    statefulset.kubernetes.io/pod-name: api-0
  ports:
    - port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
  namespace: overpass
spec:
  selector:
    matchLabels:
      app: api
  serviceName: api
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: api
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: api
          image: ghcr.io/dzfranklin/overpass-api:v0.11
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - containerPort: 80
              name: http
          env:
            - name: METRICS_API_KEY
              valueFrom:
                  secretKeyRef:
                    name: metrics-api-key
                    key: key
      volumes:
        - name: data
          hostPath:
            path: /mnt/overpass-data
